services:
  static:
    image: dai/staticwebserver
    build: 
      context: ./staticwebserver
    labels:
      - traefik.http.routers.static.rule=Host(`localhost`)
      - traefik.http.services.static.loadbalancer.server.port=9080
    deploy:
      replicas: 5
  api:
    image: dai/api
    build:
      context: ./api
    labels:
      - traefik.http.routers.api.rule=Host(`localhost`) && PathPrefix(`/api/`)
      - traefik.http.services.api.loadbalancer.server.port=7070
      - traefik.http.services.api.loadBalancer.sticky.cookie=true
      - traefik.http.services.api.loadBalancer.sticky.cookie.name=cookie_api
    deploy:
      replicas: 5
  reverse_proxy:
    image: traefik:v2.10
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock