providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          permanent: true
  https:
    address: ":443"

tls:
  certificates:
    - certFile: /etc/traefik/certificates/cert.pem
      keyFile : /etc/traefik/certificates/key.pem
      
api:
  dashboard: true
  insecure: true